### PR TITLE
Working multiple inputs

### PR DESCRIPTION
**Pull request by Kuree**
- Multi-pass on `extractparams.py` to support automatic input channel match. In other words, there is no change in the `hwconfig.user` format.
   For instance:
`hwconfig.user`:
   ```yaml
   hw:
   - type: dma
     name: dma0
     outputto: dual
   - type: dma
     name: dma1
     outputto: dual
   - type: hls
     name: dual
     path: .
     outputto: dma0
   ```
   will be translated to `hwconfig.all` automatically
   ```yaml
   hw:
   - {name: dma0, out_connected: true, outputto: dual.arg_0, type: dma}
   - {name: dma1, out_connected: false, outputto: dual.arg_1, type: dma}
   - name: dual
     outputto: dma0
     path: .
     streams:
     - {depth: 1, name: arg_0, type: input}
     - {depth: 1, name: arg_1, type: input}
     - {depth: 1, name: arg_2, type: output}
     type: hls
     vlnv: xilinx.com:hls:hls_target:1.0
   name: dual
   ```
  `mkproject.tcl.mako` has also been modified to match the channel naming scheme.
- `hwacc` will arrange the dma channel in `[input, ..., input, output]` order based on the assumption that there is only one output channel. As a result, in user space programs should prepare the buffer accordingly. If in the future we need multiple output channels, a struct indicating how to rearrange dma channels can be passed to kernel via `ioctl` command.
- Because dma controller can be designed to have only one channel, there is no need in `dtoverlay.py` script to prescribe both `dma-in` and `dma-out`. This PR merged them into `dmas` and the `hwacc` driver is going to identify input or output channels.
- Fix a memory allocation bug that causes `free_page` error and potentially PC/SP alignment error.

### CODE REVIEW

**Comment by stevenbell** [comment]
If I *do* want to specify which input goes where, is that still possible?  Obviously it doesn't matter when all the data is coming from DMA engines, but we might care if the sources were cameras or other processing pipelines.

**Comment by Kuree** [comment]
That's a very good suggestion. The current implementation assumes `hls` module receives data from DMA engine directly. Ideally you should set something like this:
```yaml
hw:
- type: csi
  name: cam0
  outputto: dual.arg_0
- type: dma
  name: dma1
  outputto: dual
- type: hls
  name: dual
  path: .
  outputto: dma0
```
`extractparams.py` should be able to finish the rest and check if there is a naming mismatch. I will work on that and make sure that works.

**Comment by Kuree** [comment]
6a4c4f2 should allow the describing scenario. However, I think this intermediate configuration should be generated by more abstract layer, such as f4graph, as `hwconfig.user` essentially describes a data flow graph.

**Comment by Kuree** [comment]
6f24863 fixed critical bug that causes zynq to hang whenever output width != 2.

**Pull request merged**
