### PR TITLE
WIP: dynamic FPGA management

### PR DESCRIPTION
**Pull request by Kuree**
This PR is a ongoing effort to let user space programs re-configure the FPGA during run-time without re-flushing kernel image.

The `hdf` file generated in SDK folder contains all the information we need to reconfigure the FPGA (the bitstream file can be included when exporting.) The workflow is as follows:
1. `unzip` the `hdf` file to a temp folder.
2. read `sysdef.xml` to obtain `hwh` file information.
3. parse `hwh` files and obtain `reg` base address and size and other information.
4. generate the `dts` file and compile it with `dtc` to get binary blob.
5. use the kernel functionality introduced in this [patch](https://lkml.org/lkml/2014/5/28/280) to overlay kernel device tree.
6. load the bitstream file into FPGA.

All these steps should be performed on the Zynq board. One of the goals is to overlay the entire information, otherwise generated as `pl.dtsi` by `petalinux-build`, to the device tree.

Current implementation notes:
+ I couldn't find any configuration on how IRQ numbers are assigned to GIC. To work around this the script uses `/proc/interrupt` table to find out free IRQ numbers.
+ It should support multiple dma modules connected to the HLS accelerator, but I haven't tested it since multi-input `tcl` is still in progress.
+ `Kconfig` needs to be modified to enable device tree overlay. I will test it out and add it to the PR once it's working.

Some thoughts:
+ I'm thinking to remove the `petalinux` build process where hardware description files are provided. Once dynamic configuration is working, there is no need to statically provide hardware description wile building the kernel.

@stevenbell @thenextged I'd really appreciate it if you can provide any suggestions or thoughts.

### CODE REVIEW

**Comment by Kuree** [comment]
+ test `hdf` file: https://transfer.sh/ndyyU/design_1_wrapper.hdf
+ `dts` file generated by petalinux: https://transfer.sh/gXVQa/pl.dtsi

You can just use `wget ${link}` to download these files.

Currently the script doesn't unzip file for you so you have to unzip the `hdf` by yourself and pass the dir as argument to the script.

**Comment by stevenbell** [comment]
A couple thoughts for the moment:
* The petalinux build flow does the GIC->IRQ mapping.  If you do a handful of tests, you can probably reverse-engineer this or find where it does the calculation.
* Unfortunately some of the FPGA design is necessary for the system to run (at least the DisplayPort), meaning that we can't just completely replace the FPGA image on the fly without causing the Linux system to hang.  It's possible to only replace part of the FPGA image (known as "partial reconfiguration"), so we'll need to do this if we want to fully embrace this approach.

**Comment by Kuree** [comment]
I came across this [patch](https://lkml.org/lkml/2015/8/13/545) on LKML that introduces FPGA manager. linux-xlnx seems to have that patch partially in their upstream, even in 2017.2 branch, see [here](https://github.com/Xilinx/linux-xlnx/tree/2017.2_video_ea/drivers/fpga). I'm wondering with that driver's suuport, is it possible to completely replace the FPGA image?

**Comment by thenextged** [comment]
I think the main issue raised by Steven still persists even with the use of that patch. To properly support dynamic hardware reconfiguration, we are going to have to find a way to do partial reconfiguration somehow. Correct me if I'm wrong, but the API provided by the patch seems to only support full reconfiguration.

**Comment by Kuree** [comment]
Did more reading and it seems like the linux kernel version of FPGA manager is capable of partial reconfiguration, or at least with minor modification.
+ partial reconfiguration [flag](https://github.com/Xilinx/linux-xlnx/blob/2017.2_video_ea/drivers/fpga/zynq-fpga.c#L191) in module source code used in petalinux 2017.2
+ a recent [paper](https://ieeexplore.ieee.org/document/8008960/) on linux kernel based FPGA manager with partial reconfiguration. 

We can discuss more tomorrow during the meeting.

**Comment by Kuree** [comment]
Closed it for now. We can revisit this once the main pipeline is working.

**Pull request closed without merging**
