### PR TITLE
hwacc rework

### PR DESCRIPTION
**Pull request by Kuree**
What's done:
- `hwacc` now spawns directly from device tree without parameterization.
- `hwacc` also binds to `hls_target` as discussed.

WIP:
1. ~~Move more control logic to `drvdata` so that multiple instance of `hwacc` can be used in user space.~~
2. ~~Need to add `phandle` to GPIO device tree entry. Currently it uses brute force search to find the intended node.~~
3. ~~Proper clean up if the module crashes in the middle of execution (tied to the first WIP list entry).~~

Some of the WIP entries are related to the future goal of this project, e.g., multiple inputs for a single HLS module and multiple HLS modules.

### CODE REVIEW

**Comment by Kuree** [comment]
@stevenbell Is `BufferList` (e.g. free_list) in `hwacc` able to handle different `hls` modules? In other words, should these buffer lists stored globally or stored per platform device if we want to support multiple `hls` modules?

It seems like `BufferList` is happy as long as it knows the dma channel controller address.

**Comment by stevenbell** [comment]
Hmm, with your changes to `BufferSet`, it should be fine to make the `free_list` global, since all the BufferSets are identical.  Obviously the intermediate processing queues need to be separate per HLS instance.  It's probably wise to make the finished queue separate as well --- we could make it global since the IDs should be unique across HLS instances, but we can avoid any complications by just making them separate.

That said, it might be better to separate the free lists as well.  That way each BufferSet can be fully allocated (i.e., the ChanBuf list can have memory allocated) beforehand, and we don't have to do any real-time memory allocations (which is kinda the whole point of the free list).  If the free list is global, then we don't have to reallocate the BufferSet objects, but we do have to reallocate (and free) the ChanBuf lists within them.

One other comment --- it seems we should have a "length" field that specifies the length of the ChanBuf array within the BufferSet struct.  I guess the length should be fully determined in any context where we use the array, but it might be a helpful safeguard...

**Comment by Kuree** [comment]
I will make these lists stored in platform device to avoid complications.

In `chan_buf` struct, `nr_channels` is the length of channel list. Since in the main `driver.c` I've set the maximum number of available channels to 0x20, `chan_buf` can be statically allocated, as you mentioned.

**Comment by Kuree** [comment]
Improvements:
1. Allow access to `cmabuffer` and `hwacc` without root privilege.
2. Block access to `hwacc` if there is another process using it (this avoids complicated concurrency problems.)
3. Completely separate kernel logic with global variables: all the variables now live in `struct hwacc_drvdata`

@stevenbell One thing I think worth discussing is should `free_list` be initialized in `dev_open()` or `hwacc_probe()`? In other words, if we put memory allocation of free_list in `hwacc_probe()`, we can clean it up whenever the device is opened without reallocating space again. Hence during the entire lifetime of `hwacc`, we only need to allocate memory once.

**Comment by stevenbell** [comment]
I think the basic tradeoff is having the memory used the whole time (larger driver footprint means less memory for the system) versus the time to allocate memory when the device is opened.  Neither of these is particularly problematic, since it's only a few KB.  I don't have any good reasons not to do the allocation as part of `hwacc_probe`, so feel free to do that.

**Comment by Kuree** [comment]
- Passed memory leak check and `rmmod`.
- All states are stored in `drvdata`.
- Add a `phandle` to GPIO in lieu of brute force search
- Generate symlink to the driver files when creating petalinux project

This module should be ready to merge now. Please let me know if you have any comments or suggestions.

**Pull request merged**
